#ifndef LIBGCC_ZEPHYR_BITS_H_
#define LIBGCC_ZEPHYR_BITS_H_

#define _POSIX_THREADS 200809L
#define _POSIX_TIMERS 200809L
#define _POSIX_MONOTONIC_CLOCK 200809L
#define _UNIX98_THREAD_MUTEX_ATTRIBUTES 1

#define _PTHREAD_MUTEX_INITIALIZER (-1)
#define _PTHREAD_COND_INITIALIZER (-1)
#define _PTHREAD_ONCE_INIT {1,0}

#endif /* LIBGCC_ZEPHYR_BITS_H_ */
